### ISSUE TITLE
You need to specify the CSV file of the Google Spreadsheet with OSIS

### ISSUE THREAD

**Issue by CrispyBacon1999** [Team694/attendance-scanner#1]
I got everything running correctly, but when trying to export, it gives me this error

`You need to specify the CSV file of the Google Spreadsheet with OSIS`

I'd love to be able to use this for our attendance!

**Comment by james9909** [comment]
In the Datastore, you need to create a Settings key named `config` and set the `osis_url` property to a link to a CSV file containing all your data.

**Comment by dannyqiu** [comment]
There's an admin panel for this. I implemented it. :) c22daba192da4ed48e0119dc106d97c23fdfb125

`/admin/settings`
